services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\QueryType\ContentSubtreeQueryType: ~

    EzSystems\EzPlatformAdminUi\QueryType\MediaSubtreeQueryType: ~
